# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ONT DEX
email: contactontdex@gmail.com
description:  On March 15, 2019, Singapore, the first decentralized trading 
              platform Ontdex (www.ontdex.io) on the new generation of 
              high-performance public chain ontology was officially launched.
baseurl: "post" # the subpath of your site, e.g. /blog
url: "contactontdex@gmail.com" # the base hostname & protocol for your site
twitter_username: OntDex Team
github_username:  Nero

# Build settings
markdown: kramdown
